baseurl: 'https://sa.sasasa.org/'
uitle: 'goliath'
source: ''
name: 'goliath'
destination: '_site'
posts: '_posts'
pages: '_pages'
tags: '_tags'
data: '_data'
includes: ''
layouts: '_layouts'
permalink: ''
exclude: ['']
host: 'localhost'
port: 573106
markdown_ext: '.md'

